# Spam Ham Classification Project Using TF-IDF And ML

In [1]:
#Bow , TF-IDF, ML Algorithms

In [2]:
import pandas as pd
data=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=["label","message"])

In [3]:
data

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
#data cleaning and data preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ravi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(data)):
    review=re.sub('[^a-zA-z]',' ',data['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

# Create Bag of Words

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100)

In [9]:
X=cv.fit_transform(corpus).toarray()

In [11]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0

In [12]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(91),
 'ok': np.int64(58),
 'free': np.int64(18),
 'win': np.int64(95),
 'text': np.int64(78),
 'txt': np.int64(87),
 'say': np.int64(69),
 'alreadi': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(93),
 'back': np.int64(4),
 'like': np.int64(40),
 'still': np.int64(74),
 'send': np.int64(71),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(64),
 'claim': np.int64(8),
 'call': np.int64(5),
 'mobil': np.int64(49),
 'co': np.int64(9),
 'home': np.int64(30),
 'want': np.int64(90),
 'today': np.int64(83),
 'cash': np.int64(7),
 'day': np.int64(12),
 'repli': np.int64(66),
 'www': np.int64(97),
 'right': np.int64(67),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(82),
 'messag': np.int64(46),
 'oh': np.int64(57),
 'ye': np.int64(98),
 'make': np.int64(44),
 'way': np.int64(92),
 'feel': np.int64(16),
 'dont': np.int64(14),
 'miss': np.int64(4

In [13]:
y=pd.get_dummies(data['label'])

In [14]:
y=y.iloc[:,0].values

In [15]:
y.shape

(5572,)

# Train Test Split

In [17]:
#Train test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.20
    
)

In [20]:
from sklearn.naive_bayes import MultinomialNB

In [21]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [23]:
spam_detect_model

MultinomialNB()

In [24]:
y_pred=spam_detect_model.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,classification_report

In [29]:
accuracy_score(y_pred,y_test)

0.9515695067264573

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.82      0.76      0.79       135
        True       0.97      0.98      0.97       980

    accuracy                           0.95      1115
   macro avg       0.90      0.87      0.88      1115
weighted avg       0.95      0.95      0.95      1115



# BOW,TFIDF,Machine Learning Algorithms
- Preprocessing And Cleaning
- Train Test Split
- BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}
- Trained Our Models

In [32]:
import pandas as pd
data=pd.read_csv('SMSSpamCollection.txt',sep="\t",names=["label","message"])

In [34]:
data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [35]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ravi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [36]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [38]:
corpus=[]
for i in range(0,len(data)):
    review=re.sub('[^a-zA-z]',' ',data['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [39]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [40]:
# Creating BoW
y=pd.get_dummies(data['label'])

In [41]:
y=y.iloc[:,0].values

In [42]:
# Train test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(corpus,y,test_size=0.20)

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [44]:
len(X_train), len(y_train)

(4457, 4457)

In [45]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [46]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [48]:
cv.vocabulary_

{'tri': np.int64(2191),
 'contact': np.int64(421),
 'last': np.int64(1108),
 'weekend': np.int64(2378),
 'draw': np.int64(573),
 'show': np.int64(1876),
 'prize': np.int64(1660),
 'guarante': np.int64(876),
 'call': np.int64(243),
 'claim': np.int64(348),
 'code': np.int64(374),
 'valid': np.int64(2291),
 'hr': np.int64(982),
 'ppm': np.int64(1643),
 'tri contact': np.int64(2192),
 'contact last': np.int64(425),
 'last weekend': np.int64(1112),
 'weekend draw': np.int64(2379),
 'draw show': np.int64(575),
 'show prize': np.int64(1878),
 'prize guarante': np.int64(1663),
 'guarante call': np.int64(877),
 'call claim': np.int64(247),
 'claim code': np.int64(350),
 'code valid': np.int64(377),
 'valid hr': np.int64(2292),
 'hr ppm': np.int64(983),
 'pay': np.int64(1550),
 'let': np.int64(1145),
 'want': np.int64(2337),
 'hous': np.int64(976),
 'say': np.int64(1811),
 'lt': np.int64(1235),
 'gt': np.int64(865),
 'st': np.int64(1971),
 'time': np.int64(2133),
 'doubl': np.int64(570),
 'chec

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [52]:
y_pred=spam_detect_model.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

0.9856502242152466
              precision    recall  f1-score   support

       False       0.92      0.96      0.94       137
        True       0.99      0.99      0.99       978

    accuracy                           0.99      1115
   macro avg       0.96      0.98      0.97      1115
weighted avg       0.99      0.99      0.99      1115



# Creating The TF-IDF Model

In [60]:
#Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(corpus,y,train_size=0.20)

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [62]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [63]:
tv.vocabulary_

{'mth': np.int64(1111),
 'half': np.int64(718),
 'price': np.int64(1445),
 'orang': np.int64(1333),
 'line': np.int64(940),
 'rental': np.int64(1635),
 'min': np.int64(1057),
 'call': np.int64(182),
 'mobileupd': np.int64(1088),
 'optout': np.int64(1332),
 'mth half': np.int64(1112),
 'half price': np.int64(720),
 'price orang': np.int64(1446),
 'orang line': np.int64(1334),
 'line rental': np.int64(941),
 'rental min': np.int64(1637),
 'min call': np.int64(1058),
 'call mobileupd': np.int64(196),
 'mobileupd call': np.int64(1089),
 'call optout': np.int64(197),
 'mm': np.int64(1077),
 'sure': np.int64(2140),
 'understood': np.int64(2296),
 'text': np.int64(2172),
 'hey': np.int64(743),
 'ho': np.int64(757),
 'weekend': np.int64(2404),
 'think': np.int64(2193),
 'chennai': np.int64(265),
 'forgot': np.int64(571),
 'come': np.int64(299),
 'auction': np.int64(95),
 'done': np.int64(434),
 'euro': np.int64(495),
 'cup': np.int64(355),
 'final': np.int64(540),
 'cash': np.int64(234),
 'col

In [64]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model=MultinomialNB().fit(X_train,y_train)

In [65]:
y_pred=spam_tfidf_model.predict(X_test)

In [66]:
print(accuracy_score(y_pred,y_test))

0.9427994616419919


In [67]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.57      1.00      0.73       345
        True       1.00      0.94      0.97      4113

    accuracy                           0.94      4458
   macro avg       0.79      0.97      0.85      4458
weighted avg       0.97      0.94      0.95      4458

